apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentinel-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "delete"]

  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch", "patch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentinel-binding
subjects:
  - kind: ServiceAccount
    name: sentinel-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: sentinel-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acs-agent
  template:
    metadata:
      labels:
        app: acs-agent
    spec:
      serviceAccountName: sentinel-account
      containers:
        - name: agent
          image: piyushdocs/acs-agent:v1
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: API_URL
              value: "http://acs-backend-service:8000"
            - name: GEMINI_API_KEY
              value: "-"
            - name: YOUR_GROQ_KEY
              value: "-"